"""jsonl 预处理 —— 把 transcript 清成 [我]/[Claude] 回合,喂切块 agent(Prompt 1)。

照真数据的噪声分类(实测 666b1f63 等)剥离:
  整条丢的 type:system / mode / permission-mode / file-history-snapshot /
              attachment / last-prompt / summary;以及 isSidechain=true(子 agent)。
  user:  纯文本里的 slash/命令/system-reminder 噪声丢;list content 的 tool_result 丢,text 留。
  assistant: thinking / tool_use 丢,只留 text。
  一个真人 turn 后常跟多条 assistant 记录(夹工具轮),合并成同一回合的 [Claude]。

产出 CleanedTranscript:回合列表(每回合带覆盖的 message-uuid,供段级 flag)+ 渲染文本。
渲染保留 Prompt 1 约定:[我]:/[Claude]: 发言,--- 分隔,行号 L1 起。
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

_DROP_TYPES = {
    "system", "mode", "permission-mode", "file-history-snapshot",
    "attachment", "last-prompt", "summary",
}

# user 纯文本里的非人类噪声:slash 命令、本地命令回显、caveat、system-reminder 包裹。
_NOISE_TAG = re.compile(
    r"^\s*<(command-name|command-message|command-args|local-command-stdout|"
    r"local-command-caveat|bash-input|bash-stdout|bash-stderr|system-reminder)\b"
)
_CAVEAT_PREFIX = "Caveat: The messages below were generated by the user"
# 系统注入的中断标记(非真人输入)
_INTERRUPT_PREFIX = "[Request interrupted by user"


@dataclass
class Turn:
    idx: int                       # 1 起
    human_text: str
    assistant_text: str
    uuids: list[str] = field(default_factory=list)  # 本回合覆盖的全部 message-uuid
    human_uuid: str | None = None
    timestamp: str | None = None   # 人类发言时间(回合锚点)


@dataclass
class CleanedTranscript:
    session_id: str
    path: str
    turns: list[Turn] = field(default_factory=list)
    skipped_sidechain: int = 0

    def to_dict(self) -> dict:
        return {
            "session_id": self.session_id,
            "path": self.path,
            "skipped_sidechain": self.skipped_sidechain,
            "turns": [
                {
                    "idx": t.idx,
                    "human_text": t.human_text,
                    "assistant_text": t.assistant_text,
                    "uuids": t.uuids,
                    "human_uuid": t.human_uuid,
                    "timestamp": t.timestamp,
                }
                for t in self.turns
            ],
        }

    @classmethod
    def from_dict(cls, d: dict) -> "CleanedTranscript":
        ct = cls(session_id=d["session_id"], path=d["path"],
                 skipped_sidechain=d.get("skipped_sidechain", 0))
        ct.turns = [
            Turn(idx=t["idx"], human_text=t["human_text"], assistant_text=t["assistant_text"],
                 uuids=t.get("uuids", []), human_uuid=t.get("human_uuid"),
                 timestamp=t.get("timestamp"))
            for t in d["turns"]
        ]
        return ct


def _is_human_text(content: str) -> bool:
    """纯文本 user content 是否真人输入(非 slash/命令/caveat/reminder 噪声)。"""
    s = content.lstrip()
    if not s:
        return False
    if _NOISE_TAG.match(s):
        return False
    if s.startswith(_CAVEAT_PREFIX):
        return False
    if s.startswith(_INTERRUPT_PREFIX):
        return False
    return True


def _user_text(content) -> str | None:
    """从 user message.content 取真人文本;噪声/工具结果返回 None。"""
    if isinstance(content, str):
        return content if _is_human_text(content) else None
    if isinstance(content, list):
        parts = [b["text"] for b in content
                 if isinstance(b, dict) and b.get("type") == "text" and b.get("text")
                 and _is_human_text(b["text"])]
        joined = "\n".join(parts).strip()
        return joined or None
    return None


def _assistant_text(content) -> str:
    """从 assistant message.content 拼 text 块(丢 thinking/tool_use)。"""
    if not isinstance(content, list):
        return ""
    parts = [b["text"] for b in content
             if isinstance(b, dict) and b.get("type") == "text" and b.get("text")]
    return "\n".join(parts).strip()


def clean(path: Path) -> CleanedTranscript:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue

    ct = CleanedTranscript(session_id=path.stem, path=str(path))
    cur: Turn | None = None

    def flush() -> None:
        nonlocal cur
        if cur is not None:
            cur.human_text = cur.human_text.strip()
            cur.assistant_text = cur.assistant_text.strip()
            ct.turns.append(cur)
            cur = None

    for r in rows:
        if not isinstance(r, dict):
            continue
        t = r.get("type")
        if t in _DROP_TYPES:
            continue
        if r.get("isSidechain"):
            ct.skipped_sidechain += 1
            continue
        msg = r.get("message") or {}
        content = msg.get("content")
        uuid = r.get("uuid")
        ts = r.get("timestamp")

        if t == "user":
            text = _user_text(content)
            if text is None:
                continue  # 工具结果 / 噪声
            flush()  # 新真人发言 = 新回合
            cur = Turn(idx=len(ct.turns) + 1, human_text=text, assistant_text="",
                       uuids=[uuid] if uuid else [], human_uuid=uuid, timestamp=ts)
        elif t == "assistant":
            text = _assistant_text(content)
            if cur is None:
                # 文件开头就是 assistant(无前置真人发言):起一个无人类发言的回合兜底
                cur = Turn(idx=len(ct.turns) + 1, human_text="", assistant_text="")
            if text:
                cur.assistant_text += ("\n" if cur.assistant_text else "") + text
            if uuid:
                cur.uuids.append(uuid)
    flush()
    return ct


def render_for_chunk(ct: CleanedTranscript) -> str:
    """切块 agent 的输入:每回合一个显式编号块【N】,杜绝按物理行计数的错位。

    回合是回映 uuid 的单位,agent 直接用回合号作 start/end,无需数行。
    多行发言原样保留在块内(块号不变)。
    """
    blocks: list[str] = []
    for t in ct.turns:
        parts = [f"【回合 {t.idx}】"]
        if t.human_text:
            parts.append(f"[我]: {t.human_text}")
        if t.assistant_text:
            parts.append(f"[Claude]: {t.assistant_text}")
        blocks.append("\n".join(parts))
    return "\n\n---\n\n".join(blocks)


def render_source_text(ct: CleanedTranscript, start_turn: int, end_turn: int) -> str:
    """把回合区间 [start_turn, end_turn] 渲染成纯对话 source_text(无回合号脚手架)。

    一文两用,同源逐字一致:① 喂提取 agent(Prompt 2)的 <source_text>;② 落成
    episode 的 source_text 正本(被 FTS 索引、被 grep/highlights 逐字命中)。
    回合号脚手架是切块的事(让 agent 输出回合号),提取与正本不需要,故剥除;
    [我]:/[Claude]: 与 --- 分隔保留,供阅读与发言归属。

    deletions(切块标的可删内容)在本步**不物理删除**:source_text 存逐字全文,
    保 grep/highlights 逐字保真;去噪交给 S5 审核界面人工做。
    """
    blocks: list[str] = []
    for t in ct.turns:
        if t.idx < start_turn or t.idx > end_turn:
            continue
        parts = []
        if t.human_text:
            parts.append(f"[我]: {t.human_text}")
        if t.assistant_text:
            parts.append(f"[Claude]: {t.assistant_text}")
        if parts:
            blocks.append("\n".join(parts))
    return "\n\n---\n\n".join(blocks)


def render(ct: CleanedTranscript) -> tuple[str, list[dict]]:
    """渲染成 [我]/[Claude] 文本(--- 分隔),返回 (文本, 行号→回合映射)。

    行号映射:每个 turn 占据的行区间 [L_start, L_end],供切块 agent 的 L-range 回映 uuid。
    """
    lines: list[str] = []
    line_map: list[dict] = []
    for t in ct.turns:
        start = len(lines) + 1
        if t.human_text:
            lines.append(f"[我]: {t.human_text}")
        if t.assistant_text:
            lines.append(f"[Claude]: {t.assistant_text}")
        end = len(lines)
        line_map.append({"idx": t.idx, "L_start": start, "L_end": end, "uuids": t.uuids})
        lines.append("---")
    text = "\n".join(lines)
    return text, line_map
